env:
  global:
    - CC_TEST_REPORTER_ID=927595a2b39ffcc289e2cb57cbd34919077c9c95445ff637159e5941cbad73f8
language: node_js
node_js:
  - "lts/*"
  - "8"
install: yarn
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn start-ci
  - cypress run
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  directories:
    - /home/travis/.cypress/Cypress