name: Prettier Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prettier:
    name: Run prettier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actionsx/prettier@v2
      with:
        args: --check .