name: Prettier Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prettier:
    name: Run prettier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: creyD/prettier_action@v4.3
      with:
        prettier_options: --check .